language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

env:
  global:
   - secure: "v2rPGWb4/cIdTIBQD8DkD3eDb8cc78KxuMM5cgHwZFcisd2ociG39Jgju+iiNU0alGSo4nPGD+AyrqPq5/G90H8dFr5fWEdFZ+I3T7NXxDJU+v5e6pydago9Bz3DMs0tokDEahG1FnYex+60/KvWWOKBMwvNRyI4s1XVd3LN4YPdqiXuQSyKAQn5qY0iEQClk5l8R6iHAYSV8LBn3Fdsjyur6Etg1+/pc8U+Sac8fwTHIcE77naVDRg0pEQCgEJB2C23OlKVdhETUJQibW4llIxKJ3lSwhx7B8OxJiqPXbI0/sFNQfl0NMR7BnPaDLbfxK3+pKK7hlyO1BYmgnpdNDEXBlafD3lgDPgLc+7hMbVnB6zefVId0dsign5yux+ejF+WqMKaVEfgoHmbZXAo7qHzGV4Mybmg3NsnILioIm3WerrSAGuRSJoIEgNi1cJ+a54ePAreD6qkuC/KcJEbcq1mYkVG7pK5T2OKJLnTeA8X/cWrCoQdtw26+e8L8G7bMhYA6lbZb90UJWmBe+bBwhsdBQzVyEHeoID1VNUnzchwFXmuB6xtvHdKUNeumXSde+aQKqRFgOJ1LYWXsLhs2BN1UpbH/tPqeCalxsVPbQlDlTAIHq7tlegoqwCWdCXHirvFwiXAFr1pIHsWAY72xlBcd+F+kwsvLTGQnAv01rQ="
   - java.util.logging.ConsoleHandler.level=WARNING

addons:
  coverity_scan:
    project:
      name: "bkimminich/kata-botwars"
      description: "Kata Bot Wars build submitted via Travis CI"
    notification_email: bjoern.kimminich@gmx.de
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: coverity_scan

after_success:
  - ./gradlew coveralls

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
